### ISSUE TITLE
Question: Is the Object SceneCaptureComponent2D Needed?

### ISSUE THREAD

**Issue by Tim-Fronsee** [code-iai/ROSIntegrationVision#19]
Currently there are 3 `SceneCaptureComponent2D`s inside `VisionComponent`.  However, only two of them publish to ROS topics, `Color` and `Depth`.  

The third one `Object` does not, so I am wondering if it is a WIP component or something from a prior implementation?

**Comment by Sanic** [comment]
Hi @Tim-Fronsee 
Are you sure that it is not accessed?
Here: https://github.com/code-iai/ROSIntegrationVision/blob/master/Source/ROSIntegrationVision/Private/VisionComponent.cpp#L246 here is a call to Object->TextureTarget

**Comment by Tim-Fronsee** [comment]
The Object capture is referenced inside the `VisionComponent`, and the `PacketBuffer` has an offset for it.

However, the data from `Object` doesn't appear to be used.  There's a [thread](https://github.com/code-iai/ROSIntegrationVision/blob/master/Source/ROSIntegrationVision/Private/VisionComponent.cpp#L162) dedicated to processing it, but it isn't actually sent to ROS (unless I'm mistaken).

Additionally, the functions [ColorAllObjects](https://github.com/code-iai/ROSIntegrationVision/blob/master/Source/ROSIntegrationVision/Private/VisionComponent.cpp#L687) and [ColorObject](https://github.com/code-iai/ROSIntegrationVision/blob/master/Source/ROSIntegrationVision/Private/VisionComponent.cpp#L639) appear to be unused as well.  `ColorObject` is referenced in `ColorAllObjects`, but `ColorAllObjects` is not referenced.  Base on their naming, I'm guessing they are meant to (or previously did) relate to the `Object` capture.  

@Sanic 
Is this a correct assumption?

**Comment by Sanic** [comment]
Hi @Tim-Fronsee 
You're right! The publishing part is missing. 
The rendering part itself was already existing, but i never managed to integrate the object mask publishing incl. the color/object mapping. I guess this is why its still in this state.

**Comment by Tim-Fronsee** [comment]
@Sanic, is there a plan to finish the feature?

**Comment by Sanic** [comment]
@Tim-Fronsee As this is an important source for machine learning related tasks, it should definitely be implemented in the future.

**Comment by Tim-Fronsee** [comment]
Understood. Thanks for the information.
