### ISSUE TITLE
changes to be able to compile the plugin on linux. warning: you need …

### ISSUE THREAD

**Issue by gonzaloaguilarjimenez** [code-iai/ROSIntegrationVision#2]
Good afternoon, 

I am writing this issue becasue I am trying to complie ROSIntegrationVision (after successfully installin ROSIntegration) for UE4 on ubuntu and I cannot.

My main problem is when I try to do: 

**_…to compile the unrealengine with -mf16c. To do this, open ./Engine/Source/Programs/UnrealBuildTool/Platform/Linux/LinuxToolChain.cs , find the GetCLArguments_Global method and add Result += f16c; in a suitable place_**

I don't really know where is the _**suitable place**_ or wether I have to write between " ". 

Is it possible that you give me an answer?

Thanks a lot.

Best regards.

**Comment by jworch** [comment]
Hi, as the documentation says:

To do this, open PATH_TO_UNREAL/Engine/Source/Programs/UnrealBuildTool/Platform/Linux/LinuxToolChain.cs, **find the GetCLArguments_Global** method

Hence, go to the GetCLArguments_Global and add 
`Result += " -mf16c";`
somewhere inside that method. For example just before the return statement is a suitable place. Just c&p the command as it is here.

**Comment by gonzaloaguilarjimenez** [comment]
Good afternoon,

I did what you said above and a pop up window jumps into the screen saying:

Missing MyProjectName  Modules
The following modules are missing or built with a different engine version:
LibUE4Editor-ROSIntegrationVision.so
Would you like to rebuild them now?

Of course I click yes and then it tries to work on it and a second pop up window jumps into the screen saying:

Error
MyProjectName could not be compiled. Try rebuilding from source manually.

Then the program crashes and sends me out.

Do you know what can be happening?

Thanks a lot.

Best regards.

**Comment by gonzaloaguilarjimenez** [comment]
Hi again,

to explain what i wrote above in a better way i attach the image below: 

![image](https://user-images.githubusercontent.com/35638894/38642207-b0cf6a96-3dd9-11e8-9a50-7456df8cf149.png)

This is what I get when I try to enable the pluging by restarting, then everything describe above happens.

Please help me.

Thanks.

**Comment by Sanic** [comment]
If the compilation fails, we need your compile log to help you any further.

**Comment by gonzaloaguilarjimenez** [comment]
Source compilation on the ubuntu terminal or i.e. visual studio? 

Should I compile whole ue4? From the beginning? The compilation is really long, what should I show you exactly?

Thanks.

**Comment by Sanic** [comment]
Hi,

i guess the ubuntu terminal output of the project build process should do it.

And yes, you need to recompile engine:

_"If you use this Plugin on Linux, you need to enable F16C support manually in Unreal Engine 4 and recompile it"_

**Comment by gonzaloaguilarjimenez** [comment]
Finally I solve it recompiling UE4 from the beginning, even generating the projects' files.

It seems to be working. 

I will do some more tests anyway.

Thanks very much.

Best regards.

**Comment by gonzaloaguilarjimenez** [comment]
Hello again,

It seems as I said some hours ago that I finally installed it, but I am not receiving the images in RVIZ (as you can see in the picture attached there is nothing received). I don't really know whether it is due to ROSIntegrationVision or due to ROSIntegration, although as you can see, ROSIntegration connects with UE4.

![image](https://user-images.githubusercontent.com/35638894/38767379-67d06cce-3fe0-11e8-8ccb-3b0ecf3ede1f.png)

![image](https://user-images.githubusercontent.com/35638894/38767386-8c1097e4-3fe0-11e8-9542-2976b38feab7.png)

Could you please help me with this? 

Thanks a lot.

Best regards.
