### ISSUE TITLE
Problem with the color image

### ISSUE THREAD

**Issue by DominikAUT** [code-iai/ROSIntegrationVision#24]
Hi there. I have a problem with the color image. It is not displayed correctly. The depth image works well. Can someone help me?

![ROS Color Image](https://user-images.githubusercontent.com/60258458/75097801-2533a200-55af-11ea-932c-181ff355ca8f.PNG)

**Comment by Sanic** [comment]
Hi,

does this also happen in a fresh example project?

**Comment by DominikAUT** [comment]
Wow, thank you for the answer, you are right, it didn‘t happen by a fresh project. What did I wrong?

**Comment by Sanic** [comment]
Maybe the rendering has problems with post processing settings,  foliages, etc.?
Could be worth a shot adding the parts of the environment to your fresh example project piece by piece

**Comment by DominikAUT** [comment]
Thank you for the hint. That worked well, I had problems with the anti aliasing setup, but there still differences in the colour reproduction. Is it normal? Many thanks in advance.

**Comment by DominikAUT** [comment]
Thank you for your prompt reply. Apparently I had problems with the anti-aliasing settings. One last question, is it possible to use PostProcess settings like Motion Blur? If I change these parameters can I can't see differences in the image?

**Comment by Sanic** [comment]
I never tried, but i think that depends on the used CaptureSource. 
For your reference:
https://github.com/code-iai/ROSIntegrationVision/blob/master/Source/ROSIntegrationVision/Private/VisionComponent.cpp#L58
